# This role binding allows "jane" to read pods in the "default" namespace.
kind: ${1:Cluster}RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
	name: ${2:read-pods}
	${3:namespace: ${4:pods}}
subjects:
- kind: ${5:User|ServiceAccount|Group}
	name: ${6:jane} # Name is case sensitive
	apiGroup: rbac.authorization.k8s.io
roleRef:
	kind: ${7:Cluster}Role #this must be Role or ClusterRole
	name: ${8:pod-reader} # this must match the name of the Role or ClusterRole you wish to bind to
	apiGroup: rbac.authorization.k8s.io
